package cz.danakut.dnd;

public enum SkillName {
    ATHLETICS,
    ACROBATICS,
    SLEIGHT_OF_HAND,
    STEALTH,
    ARCANA,
    HISTORY,
    INVESTIGATION,
    NATURE,
    RELIGION,
    ANIMAL_HANDLING,
    INSIGHT,
    MEDICINE,
    PERCEPTION,
    SURVIVAL,
    DECEPTION,
    INTIMIDATION,
    PERFORMANCE,
    PERSUASION;
}
